language: node_js
sudo: false
node_js:
  - 6
branches:
  only:
    - master
script:
  - npm run lint
  - npm run fixtures
  - npm run coveralls
after_success:
  - npm i coveralls
  - cat ./coverage/lcov.info | $(npm bin)/coveralls && echo "Coverage data was sent to coveralls!"
