language: node_js
sudo: false
matrix:
  include:
  - node_js: 6
    env: COVERALLS=1
  - node_js: 7
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+.*$/
script:
- npm run lint
- npm run fixtures
- npm run coveralls
after_success:
- |
  if [ "x$COVERALLS" = "x1" ]; then
    npm i coveralls
    cat ./coverage/lcov.info | $(npm bin)/coveralls && echo "Coverage data was sent to coveralls!"
  fi
deploy:
  provider: npm
  email: levonet@gmail.com
  api_key:
    secure: In9U75nzSuISayo9/2yCZNxJUl5Q61RyRw7XzRdoCxGZo0vEXz+tIxflAV+ipF7sc/TxLPblpf21eDlA5+ftMR8ntHMlDwFiSkOLx+9Z90aMFBLsoNKa0oW47Na6UuERmbvunO+LMpanDX0d7iciyVMdY8BjY2qQe02nNdakBIPkwjd8wZdExfW/t8r2zRioiy/puIplFNyF3ce5mxkT8CrSXfua4wpc0wjmixT7ni8B4L8v3yrjz3JvxW8i1uctOrnx1YF3vbEw5fLTKoePqKSugEhhAnN3Savy7ypc8KLhTSVL2kJXprC8usCYfpxkRj4D9bUH88RkSFZQ9C5jK1Aa/kUwkVdzn0EV+EaApwLhKwZe2ADrZ086KJTZOzt0SHy16G4wMyzc/jwmTmQONQqE2oOursKtd4T+rmj93qA4nRueL13jQxwk6zZxFCL5NU9u4QHL9Twhr653ARLXqC1ZG72Q3hdz0OgRWsMtbsgYVlZroT/a2FbFhG2YGGXPPhyksAvvkqC8TgCsMrmi6in8+H87Dl14aHMxia9g7caJjVoCXndz+h78pcJKS1GiTWX5CNRiyleyH/Kk7Dpy0chDLAOt3ZB1m4nP0ysvSKIXnV/KxMUFP69YVS1Q48nllIP7IbO81o1bI9B0jb2exdPBpqnwUzKaKgXyUKbsCk8=
  on:
    tags: true
    node: 6
